ML-1246: Support `full_event` in `StreamTarget` and `KafkaTarget`
mlrun/storey pull request #376
Opened 2022-09-13 08:56 UTC by gtopper

and read it back properly.

2022-09-15 12:50 UTC, assaf758 requested changes

2022-09-15 12:50 UTC, assaf758 commented on integration/test_flow_integration.py
> +        await controller.emit(Event(i, time=event_time, id=str(i)))
i => body=i

2022-09-15 12:50 UTC, assaf758 commented on integration/test_flow_integration.py
> +            b'{"full_event_wrapper": true, "body": 0, "time": "2022-08-08T00:00:00", "id": "0"}',
"full_event_wrapper" =>  Event._serialize_event_marker

2022-09-15 12:50 UTC, assaf758 commented on storey/dtypes.py
> +    _serialize_event_marker = 'full_event_wrapper'
how about adding a '_' prefix or even '_story' prefix to make conflicts with the user data less probable..

2022-09-15 12:50 UTC, assaf758 commented on integration/test_flow_integration.py
> +        await controller.emit(Event(json.loads(record.decode('utf8')), id='some-new-id'))
i understand the id ('some-new-id') is ignored when receiving full-event - please state this in a comment.

2022-09-18 03:10 UTC, gtopper commented on integration/test_flow_integration.py
> +        await controller.emit(Event(i, time=event_time, id=str(i)))
I don't mind changing it, but it's like that pretty much everywhere:
```
✗ grep -r 'Event(' * | wc -l 
     105
✗ grep -r 'Event(body=' * | wc -l
       4
```

2022-09-18 03:17 UTC, gtopper commented on integration/test_flow_integration.py
> +            b'{"full_event_wrapper": true, "body": 0, "time": "2022-08-08T00:00:00", "id": "0"}',
This way we get:
* a readable example that's also
* less coupled with the implementation and
* will break if we make an incompatible change

I think the last one is particularly important.

2022-09-18 03:19 UTC, gtopper commented on storey/dtypes.py
> +    _serialize_event_marker = 'full_event_wrapper'
But... How is the user going to conflict with this? They can't insert anything into the wrapper.

2022-09-18 03:21 UTC, gtopper commented on integration/test_flow_integration.py
> +        await controller.emit(Event(json.loads(record.decode('utf8')), id='some-new-id'))
I'll put it in the ID itself.

2022-09-18 07:04 UTC, assaf758 approved these changes

2022-09-18 07:04 UTC, assaf758 commented on storey/dtypes.py
> +    _serialize_event_marker = 'full_event_wrapper'
I guess can happen if _build_event() receive an event with a user "full_event_wrapper" field - but I agree it's unlikely.

2022-09-18 07:04 UTC, assaf758 commented on integration/test_flow_integration.py
> +            b'{"full_event_wrapper": true, "body": 0, "time": "2022-08-08T00:00:00", "id": "0"}',
ok

2022-09-19 03:29 UTC, merged