ML-3654 set result when using error handler in graph.
mlrun/storey pull request #429
Opened 2023-03-26 14:24 UTC by davesh0812

see also mlrun pr - https://github.com/mlrun/mlrun/pull/3341

2023-03-27 06:25 UTC, gtopper requested changes
Please see my comments on [ML-3654](https://jira.iguazeng.com/browse/ML-3654) for RCA and proposed action points.

2023-03-27 06:25 UTC, gtopper commented on storey/flow.py
> +                    event._awaitable_result._set_result(Event(body={"error_msg": message, "origin_body": event.body}))
You really can't just make up an event to put there. You're thinking about serving, but storey isn't just used for serving.

2023-03-27 06:25 UTC, gtopper commented on storey/flow.py
> +                    event._awaitable_result._set_result(Event(body={"error_msg": message, "origin_body": event.body}))
Furthermore, there was already a call to `_set_error` there, which calls `_set_result`.

2023-03-27 06:25 UTC, gtopper commented on storey/flow.py
> +                    event._awaitable_result._set_result(Event(body={"error_msg": message, "origin_body": event.body}))
It also makes no sense to set the result and then do the recovery. The recovery should lead somewhere that completes the result.

2023-03-27 06:25 UTC, gtopper commented on storey/flow.py
> +                return
The result of `await recovery_step._do(event)` should be returned as before, not `None`. This matters for flow termination.

2023-03-29 09:13 UTC, closed without merging

2023-03-29 09:14 UTC, davesh0812 commented
will redesign as discussed