ML-4799: Simplify and optimize emit source offset handling for performance
mlrun/storey pull request #462
Opened 2023-10-29 07:14 UTC by gtopper

2023-11-01 10:24 UTC, assaf758 requested changes

2023-11-01 10:24 UTC, assaf758 commented on storey/sources.py
> +      Defaults to 10,000.
20000
also please add description of max_time_before_commit

2023-11-01 10:24 UTC, assaf758 commented on storey/sources.py
> +                    events_handled_since_commit = 0
```suggestion
                    events_handled_since_last_commit = 0
```

2023-11-01 10:50 UTC, gtopper commented on storey/sources.py
> +                num_offsets_not_handled += 1
```suggestion
                num_offsets_not_committed += 1
```

2023-11-01 15:19 UTC, assaf758 commented on storey/sources.py
> +      Defaults to 10,000.
you missed adding description of max_time_before_commit

2023-11-02 09:02 UTC, assaf758 approved these changes

2023-11-02 09:05 UTC, merged