[Driver] Fix V3io Engine to handle single quote as value in df.
mlrun/storey pull request #498
Opened 2024-01-24 14:02 UTC by tomerm-iguazio

[ML-5576](https://jira.iguazeng.com/browse/ML-5576)

2024-01-25 09:09 UTC, alxtkr77 approved these changes

2024-01-25 16:04 UTC, assaf758 requested changes

2024-01-25 16:04 UTC, assaf758 commented on integration/test_flow_integration.py
> +    assert get_key_all_attrs_test_helper(setup_teardown_test, "2", keys) == {"color": "red", "num": 2}
please add a test that "gre'en" + 'bl"ue' fails.

2024-01-25 16:04 UTC, assaf758 commented on storey/drivers.py
> +            # may impact performance
please remove comment on performance (already discussed).
please add a comment that a string with both " and ' are not supported

2024-01-28 11:12 UTC, assaf758 approved these changes

2024-01-28 11:12 UTC, merged